# Generated by Django 4.0.4 on 2022-05-16 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_warehouse_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='item',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='item',
            field=models.ManyToManyField(blank=True, null=True, to='inventory.item'),
        ),
    ]
