# Generated by Django 4.0.4 on 2022-05-17 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_warehouse_item_warehouse_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse'),
        ),
    ]
