# Generated by Django 4.0.4 on 2022-05-17 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_warehouse_item_item_warehouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.item'),
        ),
    ]
