# Generated by Django 4.0.4 on 2022-05-17 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_item_warehouse_warehouse_warehouse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouse',
            old_name='warehouse',
            new_name='items',
        ),
    ]
