# Generated by Django 4.0.4 on 2022-05-17 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_warehouse_items_item_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.warehouse'),
        ),
    ]
